name: varaible demo
on:
  push:
    branches:
    - master
#Workflow level environment variable, this variable will be available to all the jobs and steps in the workflow
env:
  PYTHON_VERSION: 3.9
jobs:
  buildpyhtoncode_job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup python version ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: run python version
        run: python --version
  buildpythoncode_job2:
  #job level environment variable, this variable will be available to all the steps in this job but not in other jobs
    env:
      PYTHON_VERSION_JOB: 3.11
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup python version ${{ env.PYTHON_VERSION_JOB }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION_JOB }}
      - name: run python version
        run: python --version
  buildpythoncode_job3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup python version ${{ env.PYTHON_VERSION_STEP }}
      #step level environment variable, this variable will be available only to this step and not to other steps in the job or other jobs in the workflow
        env:
          PYTHON_VERSION_STEP: 3.12
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION_STEP }}
      - name: run python version
        run: python --version
  
